const queryMariadb = `SELECT TABLE_NAME as TABNAME, COLUMN_NAME as COLNAME, ORDINAL_POSITION as COLNO, CHARACTER_MAXIMUM_LENGTH as LENGTH,
       NUMERIC_SCALE as SCALE, COLUMN_DEFAULT as 'DEFAULT', IS_NULLABLE as 'NULLS', COLUMN_KEY as KEYSEQ
       FROM INFORMATION_SCHEMA.COLUMNS 
       where TABLE_SCHEMA = 'casaos'`;